package com.takaaki.urcap.eipmonitor.impl.rtde;

public enum RTDEInput {
    speed_slider_mask("speed_slider_mask"), /**/
    speed_slider_fraction("speed_slider_fraction"), /**/
    standard_digital_output_mask("standard_digital_output_mask"), /**/
    standard_digital_output("standard_digital_output"), /**/
    configurable_digital_output_mask("configurable_digital_output_mask"), /**/
    configurable_digital_output("configurable_digital_output"), /**/
    tool_digital_output_mask("tool_digital_output_mask"), /**/
    tool_digital_output("tool_digital_output"), /**/
    standard_analog_output_mask("standard_analog_output_mask"), /**/
    standard_analog_output_type("standard_analog_output_type"), /**/
    standard_analog_output_0("standard_analog_output_0"), /**/
    standard_analog_output_1("standard_analog_output_1"), /**/
    input_bit_registers0_to_31("input_bit_registers0_to_31"), /**/
    input_bit_registers32_to_63("input_bit_registers32_to_63"), /**/
    input_bit_register_64("input_bit_register_64"), /**/
    input_bit_register_65("input_bit_register_65"), /**/
    input_bit_register_66("input_bit_register_66"), /**/
    input_bit_register_67("input_bit_register_67"), /**/
    input_bit_register_68("input_bit_register_68"), /**/
    input_bit_register_69("input_bit_register_69"), /**/
    input_bit_register_70("input_bit_register_70"), /**/
    input_bit_register_71("input_bit_register_71"), /**/
    input_bit_register_72("input_bit_register_72"), /**/
    input_bit_register_73("input_bit_register_73"), /**/
    input_bit_register_74("input_bit_register_74"), /**/
    input_bit_register_75("input_bit_register_75"), /**/
    input_bit_register_76("input_bit_register_76"), /**/
    input_bit_register_77("input_bit_register_77"), /**/
    input_bit_register_78("input_bit_register_78"), /**/
    input_bit_register_79("input_bit_register_79"), /**/
    input_bit_register_80("input_bit_register_80"), /**/
    input_bit_register_81("input_bit_register_81"), /**/
    input_bit_register_82("input_bit_register_82"), /**/
    input_bit_register_83("input_bit_register_83"), /**/
    input_bit_register_84("input_bit_register_84"), /**/
    input_bit_register_85("input_bit_register_85"), /**/
    input_bit_register_86("input_bit_register_86"), /**/
    input_bit_register_87("input_bit_register_87"), /**/
    input_bit_register_88("input_bit_register_88"), /**/
    input_bit_register_89("input_bit_register_89"), /**/
    input_bit_register_90("input_bit_register_90"), /**/
    input_bit_register_91("input_bit_register_91"), /**/
    input_bit_register_92("input_bit_register_92"), /**/
    input_bit_register_93("input_bit_register_93"), /**/
    input_bit_register_94("input_bit_register_94"), /**/
    input_bit_register_95("input_bit_register_95"), /**/
    input_bit_register_96("input_bit_register_96"), /**/
    input_bit_register_97("input_bit_register_97"), /**/
    input_bit_register_98("input_bit_register_98"), /**/
    input_bit_register_99("input_bit_register_99"), /**/
    input_bit_register_100("input_bit_register_100"), /**/
    input_bit_register_101("input_bit_register_101"), /**/
    input_bit_register_102("input_bit_register_102"), /**/
    input_bit_register_103("input_bit_register_103"), /**/
    input_bit_register_104("input_bit_register_104"), /**/
    input_bit_register_105("input_bit_register_105"), /**/
    input_bit_register_106("input_bit_register_106"), /**/
    input_bit_register_107("input_bit_register_107"), /**/
    input_bit_register_108("input_bit_register_108"), /**/
    input_bit_register_109("input_bit_register_109"), /**/
    input_bit_register_110("input_bit_register_110"), /**/
    input_bit_register_111("input_bit_register_111"), /**/
    input_bit_register_112("input_bit_register_112"), /**/
    input_bit_register_113("input_bit_register_113"), /**/
    input_bit_register_114("input_bit_register_114"), /**/
    input_bit_register_115("input_bit_register_115"), /**/
    input_bit_register_116("input_bit_register_116"), /**/
    input_bit_register_117("input_bit_register_117"), /**/
    input_bit_register_118("input_bit_register_118"), /**/
    input_bit_register_119("input_bit_register_119"), /**/
    input_bit_register_120("input_bit_register_120"), /**/
    input_bit_register_121("input_bit_register_121"), /**/
    input_bit_register_122("input_bit_register_122"), /**/
    input_bit_register_123("input_bit_register_123"), /**/
    input_bit_register_124("input_bit_register_124"), /**/
    input_bit_register_125("input_bit_register_125"), /**/
    input_bit_register_126("input_bit_register_126"), /**/
    input_bit_register_127("input_bit_register_127"), /**/
    input_int_register_0("input_int_register_0"), /**/
    input_int_register_1("input_int_register_1"), /**/
    input_int_register_2("input_int_register_2"), /**/
    input_int_register_3("input_int_register_3"), /**/
    input_int_register_4("input_int_register_4"), /**/
    input_int_register_5("input_int_register_5"), /**/
    input_int_register_6("input_int_register_6"), /**/
    input_int_register_7("input_int_register_7"), /**/
    input_int_register_8("input_int_register_8"), /**/
    input_int_register_9("input_int_register_9"), /**/
    input_int_register_10("input_int_register_10"), /**/
    input_int_register_11("input_int_register_11"), /**/
    input_int_register_12("input_int_register_12"), /**/
    input_int_register_13("input_int_register_13"), /**/
    input_int_register_14("input_int_register_14"), /**/
    input_int_register_15("input_int_register_15"), /**/
    input_int_register_16("input_int_register_16"), /**/
    input_int_register_17("input_int_register_17"), /**/
    input_int_register_18("input_int_register_18"), /**/
    input_int_register_19("input_int_register_19"), /**/
    input_int_register_20("input_int_register_20"), /**/
    input_int_register_21("input_int_register_21"), /**/
    input_int_register_22("input_int_register_22"), /**/
    input_int_register_23("input_int_register_23"), /**/
    input_int_register_24("input_int_register_24"), /**/
    input_int_register_25("input_int_register_25"), /**/
    input_int_register_26("input_int_register_26"), /**/
    input_int_register_27("input_int_register_27"), /**/
    input_int_register_28("input_int_register_28"), /**/
    input_int_register_29("input_int_register_29"), /**/
    input_int_register_30("input_int_register_30"), /**/
    input_int_register_31("input_int_register_31"), /**/
    input_int_register_32("input_int_register_32"), /**/
    input_int_register_33("input_int_register_33"), /**/
    input_int_register_34("input_int_register_34"), /**/
    input_int_register_35("input_int_register_35"), /**/
    input_int_register_36("input_int_register_36"), /**/
    input_int_register_37("input_int_register_37"), /**/
    input_int_register_38("input_int_register_38"), /**/
    input_int_register_39("input_int_register_39"), /**/
    input_int_register_40("input_int_register_40"), /**/
    input_int_register_41("input_int_register_41"), /**/
    input_int_register_42("input_int_register_42"), /**/
    input_int_register_43("input_int_register_43"), /**/
    input_int_register_44("input_int_register_44"), /**/
    input_int_register_45("input_int_register_45"), /**/
    input_int_register_46("input_int_register_46"), /**/
    input_int_register_47("input_int_register_47"), /**/
    input_double_register_0("input_double_register_0"), /**/
    input_double_register_1("input_double_register_1"), /**/
    input_double_register_2("input_double_register_2"), /**/
    input_double_register_3("input_double_register_3"), /**/
    input_double_register_4("input_double_register_4"), /**/
    input_double_register_5("input_double_register_5"), /**/
    input_double_register_6("input_double_register_6"), /**/
    input_double_register_7("input_double_register_7"), /**/
    input_double_register_8("input_double_register_8"), /**/
    input_double_register_9("input_double_register_9"), /**/
    input_double_register_10("input_double_register_10"), /**/
    input_double_register_11("input_double_register_11"), /**/
    input_double_register_12("input_double_register_12"), /**/
    input_double_register_13("input_double_register_13"), /**/
    input_double_register_14("input_double_register_14"), /**/
    input_double_register_15("input_double_register_15"), /**/
    input_double_register_16("input_double_register_16"), /**/
    input_double_register_17("input_double_register_17"), /**/
    input_double_register_18("input_double_register_18"), /**/
    input_double_register_19("input_double_register_19"), /**/
    input_double_register_20("input_double_register_20"), /**/
    input_double_register_21("input_double_register_21"), /**/
    input_double_register_22("input_double_register_22"), /**/
    input_double_register_23("input_double_register_23"), /**/
    input_double_register_24("input_double_register_24"), /**/
    input_double_register_25("input_double_register_25"), /**/
    input_double_register_26("input_double_register_26"), /**/
    input_double_register_27("input_double_register_27"), /**/
    input_double_register_28("input_double_register_28"), /**/
    input_double_register_29("input_double_register_29"), /**/
    input_double_register_30("input_double_register_30"), /**/
    input_double_register_31("input_double_register_31"), /**/
    input_double_register_32("input_double_register_32"), /**/
    input_double_register_33("input_double_register_33"), /**/
    input_double_register_34("input_double_register_34"), /**/
    input_double_register_35("input_double_register_35"), /**/
    input_double_register_36("input_double_register_36"), /**/
    input_double_register_37("input_double_register_37"), /**/
    input_double_register_38("input_double_register_38"), /**/
    input_double_register_39("input_double_register_39"), /**/
    input_double_register_40("input_double_register_40"), /**/
    input_double_register_41("input_double_register_41"), /**/
    input_double_register_42("input_double_register_42"), /**/
    input_double_register_43("input_double_register_43"), /**/
    input_double_register_44("input_double_register_44"), /**/
    input_double_register_45("input_double_register_45"), /**/
    input_double_register_46("input_double_register_46"), /**/
    input_double_register_47("input_double_register_47");

    private String type;

    private RTDEInput(String type) {
        this.type = type;
    }

    public String getType() {
        return type;
    }

}
